
package Day4coding;
public class Day4coding100 {
    public static void main(String[] args) {
        
        
      System.out.println("Nama \t \t: Rusmiati");
      System.out.println("Nim \t \t: D0225016");
      System.out.println("Alamat \t \t: Pasangkayu");
      System.out.println("Prodi \t \t: Informatika");
      System.out.println("Jenis Kelamin \t: Perempuan");
 
      System.out.println("Nama \t \t:Rusmiati \nNim \t \t:D0225016 \nAlamat \t \t:Pasangkayu \nProdi \t\t:Informatika \nJenis Kelamin \t:Perempuan");
          
    }
    
}
