
package Minggu1;
import java.util.Scanner;
public class Day011 {
    
    public static void main(String[] args) {
        Scanner input = new Scanner (System.in);
        
        System.out.print("masukkan nama :");
        String Nama = input.nextLine();
        
        System.out.print("masukkan tinggi badan :");
        double Tinggi = input.nextDouble();
        
        System.out.print("masukkan umur :");
        int umur = input.nextInt();
        
        System.out.print("masukkan tanggal lahir :");
        char Tanggal_Lahir = input.next().charAt(30); 
        
 
        
        //System.out.println("\n-----data yang dimasukkan-----");
        //System.out.println("masukkan nama          : + nama");
        //System.out.println("masukkan tinggi badan  : + tinggi");
        //System.out.println("masukkan tanggal lahir : + tanggal lahir");
        //System.out.println("masukkan umur          : + umur");
       
        
        
    }
    
}
