
package Minggu2;

import java.util.Scanner;

public class Days023 {
    public static void main(String[] args) {
        Scanner input = new Scanner(System.in);
        
        System.out.print("Masukkan Panjang Persegi : ");
        int Panjang = input.nextInt();
        
        System.out.print("Masukkan Lebar Persegi : ");
        int Lebar = input.nextInt();
        
        int Luas = Panjang*Lebar;
        
        System.out.println("Luas Persegi Panjang : " + Luas);
        
        
        
        
    }
    
}
