
package Day7coding;

public class Day7coding100 {
    public static void main(String[] args) {
        char jenis_kelamin = 'P';
        char simbol = '!';
        char huruf_pertama_nama_saya = 'R';
        boolean apakah_saya_lulus = true;
        boolean apakah_dia_setuju = false;
        
        System.out.println(jenis_kelamin);
        System.out.println(simbol);
        System.out.println(huruf_pertama_nama_saya);
        System.out.println(apakah_saya_lulus);
        System.out.println(apakah_dia_setuju);
    }
    
}
