
package Minggu6;

public class Days081 {
    public static void main(String[] args) {
        
        int[] Angka = {10, 20, 30, 40, 50, 60, 70};
        
        System.out.println("Index ke- 0 " + Angka[0]);
        System.out.println("Index ke- 1 " + Angka[1]);
        System.out.println("Index ke- 2 " + Angka[2]);
        System.out.println("Index ke- 3 " + Angka[3]);
        System.out.println("Index ke- 4 " + Angka[4]);
        System.out.println("Index ke- 4 " + Angka[5]);
        System.out.println("Index ke- 4 " + Angka[6]);
        
    }
    
}
