
package Minggu3;

import java.util.Scanner;

public class Days028 {
    public static void main(String[] args) {
        Scanner input = new Scanner(System.in);
        
        System.out.print("Masukkan Nilai A : ");
        int A = input.nextInt();
        
        System.out.print("Masukkan Nilai B : ");
        int B = input.nextInt();
        
        
        System.out.println("A == B " + (A == B));
        System.out.println("A != B " + (A != B));
    }
    
}
