
package Minggu2;
public class Day026 {
    public static void main(String[] args) {
        
        int A = 8, T = 6, I = 4, K = 1, S = 6;
        A += 3;
        T -= 3;
        I *= 5;
        K /= 2;
        S %= 8;
        
        System.out.println("Hasil A : " + A);
        System.out.println("Hasil T : " + T);
        System.out.println("Hasil I : " + I);
        System.out.println("Hasil K : " + K);
        System.out.println("Hasil S : " + S);
        
    }
    
}
