/*
komentar ini lebih dari satu baris biasanya dipakai untuk penjelasan panjang
*/
/*
package digunakan untuk mengelompokkan class supaya rapi  
*/
package Day3coding;

/**
* untuk penjelasan yang lebih rapi dan detail
* @author Rusmi
*/
/**
 * public clas dipakai untuk class utama yang berisi method
 * @author Rusmi 
 */
public class Day3coding100 {
    
    // method utama dalam java
    public static void main(String[] args) {
     
// menampilkan teks ke layar
// untuk komentar singkat
System.out.println("Rusmiati");


    }
}
