
package Minggu7;

public class Days094 {
    public static void main(String[] args) {
         Halo();
         Profil("rusmi",19,"D0225016");
         
    }
       public static void Halo() {
        System.out.println("Halo");
    }
     public static void Profil(String nama, int umur,String nim){
        System.out.println("nama saya " + nama);
        System.out.println("umur saya " + umur);
        System.out.println("nim saya " + nim);   
    }
    
}
