
package Day9coding;

public class Day9coding100 {
    public static void main(String[] args) {
        //Deklarasi
        String Nama;
        int Umur ;
        double berat_badan;
        char jenis_kelamin;
        System.out.println("Rusmiati");
        System.out.println(19);
        System.out.println(55.0);
        System.out.println('p');
        
        //inisialisasi
        Nama = "Rusmiati";
        Umur = 19;
        berat_badan = 55.0;
        jenis_kelamin = 'P';
        System.out.println(Nama);
        System.out.println(Umur);
        System.out.println(berat_badan);
        System.out.println(jenis_kelamin);
        
        
        //Update variable
        Nama = "Rusmi";
        Umur = 20;
        berat_badan = 55.0;
        jenis_kelamin = 'P';
        System.out.println(Nama);
        System.out.println(Umur);
        System.out.println(jenis_kelamin);
        System.out.println(berat_badan);
    }
    
}
