
package Day8coding;

public class Day8coding100 {
    public static void main(String[] args) {
        String Nama = "Rusmiati";
        String Umur = "19";
        String Prodi = "Informatika";
        String Motto = "Menolong orang lain adalah seni menolong diri sendiri dikemudian hari";
        
        System.out.println("Halo perkenalkan saya " + Nama);
        System.out.println("Saya Berusia " + Umur);
        System.out.println("Saya berasal dari Prodi " + Prodi);
        System.out.println("Adapun Motto dari saya yaitu  " + Motto  );
    }
}
