
package Minggu7;

public class Days095 {
    public static void main(String[] args) {
        
        
        Nama("Rusmi");
        Umur(19);
        Tinggi(150);
    }
    public static void Nama(String nama) {
        System.out.println("Nama saya : " + nama);
    }

    public static void Umur(int umur) {
        System.out.println("Umur saya : " + umur);
    }

    public static void Tinggi(double tinggi) {
        System.out.println("Tinggi saya : " + tinggi);
    }
    
}
