
package Minggu2;
public class Days020 {
    public static void main(String[] args) {
       double nilai = 4.5;
       int angka = 34;
       float jumlah = 3f;
       boolean true_false = true;
       
       String nilai2 = String.valueOf(nilai);
       String angak2 = String.valueOf(angka);
       String jumlah2 = String.valueOf(jumlah);
       String true_false2 = String.valueOf(true_false);
       
       
       System.out.println(nilai);
       System.out.println(angka);
       System.out.println(jumlah);
       System.out.println(true_false);
    }
    
}
